inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - vendor/bundle/*

Rails/HttpPositionalArguments:
  Enabled: false

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
